### ISSUE TITLE
update to latest gitlab version?

### ISSUE THREAD

**Issue by MarkRBM** [freenas/iocage-plugin-gitlab#2]
Was delighted to get gitlab up and running so easily on freenas 11.2.  This plugin appears to be installing 10.7.5.  Current version is 11.1.1 I believe, any chance in updating the plugin to support that version? I tried looking through the template to find where the install is actually done so I could possibly do a pr but it didnt pop out to me.

**Comment by dlavigne** [comment]
Mark: instructions are here: http://doc.freenas.org/11.2/plugins.html#create-a-plugin.

**Comment by MiwiDots** [comment]
Hi Mark,
Thanks for your feedback, We will update the plugin hopefully around next week.

**Comment by MiwiDots** [comment]
Time have been passed ;-)
