### ISSUE TITLE
gitaly is missing?

### ISSUE THREAD

**Issue by TrojanCoder** [freenas/iocage-plugin-gitlab#5]
I've installed the latest version of this plugin and got errors when trying to create projects. As far as I can tell this is happening because gitaly.socket is not present in /usr/local/www/gitlab-ce/tmp/sockets/private/

Is this the right place to open a ticket or is this caused somewhere upstream?

**Comment by MiwiDots** [comment]
Hi,

Yes is the right place, did you make an update to the latest version or did you install fresh?

**Comment by MiwiDots** [comment]
Please login to your jail and do following steps:

```
su -l git -c "mkdir -p /usr/local/git/repositories"
chown git /usr/local/git/repositories
chgrp git /usr/local/git/repositories
chmod 2770 /usr/local/git/repositories
```

Restart gitlab and it should works. Please let me know if that works for you.

**Comment by TrojanCoder** [comment]
Thanks it looks like that fixed it!
