### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by ironblaster** [freenas/iocage-plugin-gitlab#9]
i install gitlab whit this command
` iocage fetch -P --name gitlab ip4_addr=" bce1 | 172.16.16.32/21" --branch 'master'` 

the ip and sub its ok

this is the message:
`Plugin: GitLab
  Official Plugin: True
  Using RELEASE: 11.2-RELEASE
  Using Branch: master
  Post-install Artifact: https://github.com/freenas/iocage-plugin-gitlab.git
  These pkgs will be installed:
    - www/gitlab-ce
    - databases/postgresql95-server
    - databases/postgresql95-contrib
    - www/nginx
gitlab is already running!
`

if i go in the jail shell show this:

`jexec: jail_attach(31): Not a directory`

**Comment by MiwiDots** [comment]
hi,

Please run iocage fetch -P --name gitlab ip4_addr=" bce1 | 172.16.16.32/21" --branch '11.2-RELEASE'.

**Comment by ironblaster** [comment]
thanks
